### ISSUE TITLE
Hello, I am very interested in the fusion of GPS and SLAM. When will your code be updated? Can I retrieve your paper?

### ISSUE THREAD

**Issue by taoyang1994** [GSORF/Visual-GPS-SLAM#2]
Thank you very much。

**Comment by GSORF** [comment]
Hello @taoyang1994,

Thank you for your question. I am very sorry for my late answer.
The code for the DSO is in its final state, although I found some issues with the current implementation (i.e. supporting tight or ultra-tight coupling with GPS). I just added the examples for the HTML5 Sensor Recorder and GPS Track Viewer on the website. I also added a few of the very first student round presentations, some images and a video as well.

Please see the updates over at https://master.kalisz.co/

I will constantly update the website with content over christmas. I should be able to publish the research papers and thesis after February 2019, as this is when the conference takes place. If you wish to get anything specific from my research please tell me.

Kind regards,
Adam

**Comment by GSORF** [comment]
Hello @taoyang1994,

the papers have now been added to the README, therefore I will close this issue:

1. VISAPP 2019: "B-SLAM-SIM: A novel approach to evaluate the fusion of Visual SLAM and GPS by example of Direct Sparse Odometry and Blender" by Adam Kalisz, Florian Particke, Dominik Penk, Markus Hiller and Jörn Thielecke. Link (VISAPP technical program): http://insticc.org/node/TechnicalProgram/visigrapp/presentationDetails/73753
2. DICTA 2018: "Systematic Analysis of Direct Sparse Odometry" by Florian Particke, Adam Kalisz, Christian Hofmann, Markus Hiller, Henrik Bey and Jörn Thielecke. Link (IEEEXPLORE): https://ieeexplore.ieee.org/document/8615807

Kind regards,
Adam
