### ISSUE TITLE
Add-on installation problem

### ISSUE THREAD

**Issue by lizeyu000-code** [GSORF/Visual-GPS-SLAM#7]
Hi! I am really interested in using your add-ons in Blender. When I install the add-on, it has the following error. Could you give me some hints about this?

![image](https://user-images.githubusercontent.com/58662140/190174003-8663c707-39a1-4ca3-b87e-26cc24686f37.png)

The error occurs on：

![image](https://user-images.githubusercontent.com/58662140/190177530-8e7abeba-e6c9-4b9d-9ae3-8b53515d5315.png)

**Comment by GSORF** [comment]
Hi @lizeyu000-code,

Thank you for telling me about the issue. I will try to reproduce the error. Could you please tell me what Blenderversion your are using? Is it still version 2.80? you can check it on the bottom right in Blender.

Also which python script did you choose from my repository? I have updated my addon for Blender 3.x but maybe the most recent version is not yet supported. If you can provide me the answers I will try to reproduce your error.

Also please do not install the addon via the user preferences but load it into the script editor and run the script.

Kind regards,
Adam

**Comment by lizeyu000-code** [comment]
These errors occur when I use them via user preference. But when I copy the lines  from addon_vslam_groundtruth_Blender280.py, and run it in the scripting window, and click "run script". Nothing shows up, and no warings or errors shows up.

Blender shows like this:
![image](https://user-images.githubusercontent.com/58662140/190408859-386dd0ca-2c10-44c9-a40f-7e5d191ef445.png)


The blender version I use is 2.80.75. and I tried the python script of 2.80, which is addon_vslam_groundtruth_Blender280.

I just wonder if I did the incorrect operation on blender. Appreciated that if any suggestions.

Thank you very much!
Zeyu Li

**Comment by GSORF** [comment]
Hi Zeyu,

Ok, that's a good sign, that you are not getting any errors! From your screenshot it looks like you now just have to go to the "Scene" settings in the properties window (lower right corner, Icon with the cone, sphere and dot). You can check my explanation in the README here and compare my screenshot: https://github.com/GSORF/Visual-GPS-SLAM#installation

Hope this helps! Feel free to ask if anything is still unclear.
Also, if you can, you may want to update to Blender 3 to have the most recent version of my addon.

Kind regards,
Adam

**Comment by lizeyu000-code** [comment]
Thank you very much! The add-on works. I am still trying to import new models in Blender to make the simulation real.

**Comment by GSORF** [comment]
Great to read that @lizeyu000-code - would love to hear from you again if there are any updates on your project. Feel free to re-open another issue if you have any problems with my addon.

Wish you success on your projects and kind regards,
Adam
